### ISSUE TITLE
Broken cache with buildFeatures.compose

### ISSUE THREAD

**Issue by MichalKlusak** [qdsfdhvh/compose-imageloader#125] opened 2023-04-19 14:38 UTC
Image cache is not working when buildFeatures.compose is set to true. When Image is recomposed, library try to download image from url again and not hit the cache. When buildFeatures.compose is turned off, the cache is working.

```
diskCacheConfig {
    directory(context.applicationContext.cacheDir.toOkioPath())
    maxSizeBytes(512L * 1024 * 1024) // 512MB
}
```

Versions:
Kotlin = 1.8.10
Gradle = 8.0.2
AGP = 7.4.2
Compose = 1.3.1 (multiplatform)
ImageLoader = 1.3.1 (for 1.4.0 the same result)

**Comment by qdsfdhvh** [comment] 2023-04-20 00:55
Hi, thanks for using, `buildFeatures.compose` and cache should not be related, I think it should be caused by other problems, can you provide a reivew demo?

**Comment by qdsfdhvh** [comment] 2023-08-27 06:27
I'm close this issue, you can reopen it if still have problem.

**Closed by qdsfdhvh** 2023-08-27 06:27 UTC
